# SPDX-FileCopyrightText: 2024 Shun Sakai
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

[tool.bumpversion]
current_version = "0.2.0"

[[tool.bumpversion.files]]
filename = "cmd/glzip/main.go"

[[tool.bumpversion.files]]
filename = "docs/man/man1/glzip.1.adoc"
