// SPDX-FileCopyrightText: 2024 Shun Sakai
//
// SPDX-License-Identifier: CC-BY-4.0

= glzip(1)
// Specify in UTC.
:docdate: 2024-08-01
:doctype: manpage
:mansource: glzip 0.3.5
:manmanual: General Commands Manual
:lzip-spec-url: https://www.nongnu.org/lzip/manual/lzip_manual.html#File-format

== NAME

glzip - reduces the size of files

== SYNOPSIS

*{manname}* [_OPTION_]... [_FILE_]...

== DESCRIPTION

*{manname}* is a simple command-line utility for reading and writing of
{lzip-spec-url}[lzip format] compressed files.

The lzip format uses a simplified form of the LZMA stream format. In most
cases, *{manname}* achieves better compression ratios than alternatives such as
*gzip*(1) and *bzip2*(1). Decompression speed is faster than *bzip2*(1), but
slower than *gzip*(1).

== POSITIONAL ARGUMENTS

_FILE_::

  Input file.

== OPTIONS

*-stdout*::

  Write to standard output, keep input files.

*-decompress*::

  Decompress data.

*-keep*::

  Keep input files.

*-dictionary-size* _BYTE_::

  Set dictionary size in bytes. Default is 8388608 (8 MiB).

*-h*, *-help*::

  Print help message.

*-version*::

  Print version number.

== EXIT STATUS

*0*::

  Successful program execution.

*1*::

  An error occurred.

== NOTES

Source repository:{blank}::

  https://github.com/sorairolake/lzip-go

== EXAMPLES

Compress the given file:{blank}::

  $ *glzip test.txt*

Keep the given file after compression:{blank}::

  $ *glzip -keep test.txt*

Compress with the specified dictionary size:{blank}::

  $ *glzip -dictionary-size 4194304 test.txt*

Decompress the given lzip file:{blank}::

  $ *glzip -decompress test.txt.lz*

Write the decompressed result to standard output:{blank}::

  $ *glzip -decompress -stdout test.txt.lz > test.txt*

== REPORTING BUGS

Report bugs to:{blank}::

  https://github.com/sorairolake/lzip-go/issues

== COPYRIGHT

Copyright (C) 2024 Shun Sakai

. This program is distributed under the terms of either the Apache License 2.0
  or the MIT License.
. This manual page is distributed under the terms of the Creative Commons
  Attribution 4.0 International Public License.

This is free software: you are free to change and redistribute it. There is NO
WARRANTY, to the extent permitted by law.

== SEE ALSO

*bzip2*(1), *gzip*(1), *lzip*(1)
