// SPDX-FileCopyrightText: 2024 Shun Sakai
//
// SPDX-License-Identifier: CC-BY-4.0

= glzip(1)
// Specify in UTC.
:docdate: 2024-04-04
:doctype: manpage
:mansource: glzip 0.3.2
:manmanual: General Commands Manual
:includedir: ../include

== NAME

glzip - reduces the size of files

== SYNOPSIS

*{manname}* [_OPTION_]... [_FILE_]...

== DESCRIPTION

*{manname}* is a simple command-line utility for reading and writing of lzip
format compressed files.

== POSITIONAL ARGUMENTS

_FILE_::

  Input file.

== OPTIONS

*-stdout*::

  Write to standard output, keep input files.

*-decompress*::

  Decompress data.

*-keep*::

  Keep input files.

*-dictionary-size* _BYTE_::

  Set dictionary size in bytes.

*-h*, *-help*::

  Print help message.

*-version*::

  Print version number.

== EXIT STATUS

*0*::

  Successful program execution.

*1*::

  An error occurred.

== NOTES

Source repository:{blank}::

  https://github.com/sorairolake/lzip-go

== EXAMPLES

Compress the given file:{blank}::

  $ *glzip test.txt*

Decompress the given lzip file:{blank}::

  $ *glzip -decompress test.txt.lz*

== REPORTING BUGS

Report bugs to:{blank}::

  https://github.com/sorairolake/lzip-go/issues

== COPYRIGHT

Copyright (C) 2024 Shun Sakai

. This program is distributed under the terms of either the Apache License 2.0
  or the MIT License.
. This manual page is distributed under the terms of the Creative Commons
  Attribution 4.0 International Public License.

This is free software: you are free to change and redistribute it. There is NO
WARRANTY, to the extent permitted by law.

== SEE ALSO

*lzip*(1)
